application: stacks
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: routes.py

- url: /index\.html
  script: routes.py

- url: /api/.*
  script: routes.py
  login: required
  auth_fail_action: unauthorized

- url: /admin/.*
  script: routes.py
  login: admin

- url: /.*
  static_dir: app
