application: stacks
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: app/css

- url: /img
  static_dir: app/img

- url: /js
  static_dir: app/js

- url: /lib
  static_dir: app/lib

- url: /partials
  static_dir: app/partials

- url: /protorpc.*
  script: routes.py

- url: /api/.*
  script: routes.py
  login: required
  auth_fail_action: unauthorized

- url: /tasks/.*
  script: routes.py
  login: admin

- url: /admin/.*
  script: routes.py
  login: admin

- url: /
  script: routes.py
